# Generated by Django 2.2.1 on 2020-02-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0005_blueprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blueprint',
            old_name='workflow_id',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='datum',
            old_name='node_id',
            new_name='node',
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='datum_id',
            new_name='datum',
        ),
        migrations.RenameField(
            model_name='definition',
            old_name='sample_id',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='figure',
            old_name='process_id',
            new_name='process',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='experiment_id',
            new_name='experiment',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='metavalue',
            old_name='metakey_id',
            new_name='metakey',
        ),
        migrations.RenameField(
            model_name='metavalue',
            old_name='process_id',
            new_name='process',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='process_id',
            new_name='process',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='workflow_id',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='property_id',
            new_name='property',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='experiment_id',
            new_name='experiment',
        ),
    ]
