# Generated by Django 2.2.1 on 2020-03-02 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0007_auto_20200227_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.Experiment'),
        ),
    ]
