# Generated by Django 2.2.1 on 2020-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0008_auto_20200302_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='figure',
            name='figure_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='metakey',
            name='key_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='boxid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workflow_name',
            field=models.CharField(max_length=255),
        ),
    ]
