# Generated by Django 2.2.1 on 2020-03-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0009_auto_20200302_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
