# Generated by Django 2.2.1 on 2020-03-13 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0010_auto_20200306_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='si',
            new_name='base',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='property',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.Unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='symbol',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
