# Generated by Django 2.2.1 on 2020-03-13 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapi', '0011_auto_20200313_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='unit',
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Unit')),
            ],
        ),
    ]
