# Generated by Django 2.2.1 on 2020-03-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0012_auto_20200313_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
