# Generated by Django 2.2.1 on 2020-03-25 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0013_auto_20200313_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='typeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Type'),
        ),
    ]
