# Generated by Django 2.2.1 on 2020-03-26 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0014_auto_20200325_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datum',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datum',
            name='finisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datum',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Node'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='figure',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='figure',
            name='property_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_x', to='webapi.Property'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='property_y',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_y', to='webapi.Property'),
        ),
        migrations.AlterField(
            model_name='metakey',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metavalue',
            name='metakey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Metakey'),
        ),
        migrations.AlterField(
            model_name='metavalue',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Process'),
        ),
        migrations.AlterField(
            model_name='node',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='node',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Process'),
        ),
        migrations.AlterField(
            model_name='process',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='type',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapi.Experiment'),
        ),
    ]
