# Generated by Django 2.2.1 on 2020-03-26 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0016_auto_20200326_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Property'),
        ),
    ]
