# Generated by Django 2.2.1 on 2020-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0018_auto_20200330_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='datatype',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Datatype',
        ),
    ]
