# Generated by Django 2.2.1 on 2020-03-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0019_auto_20200330_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='datatype',
            field=models.IntegerField(default=0),
        ),
    ]
