# Generated by Django 2.2.1 on 2020-04-21 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0020_auto_20200331_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='workflow',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='blueprint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Blueprint'),
            preserve_default=False,
        ),
    ]
