# Generated by Django 2.2.1 on 2020-04-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0022_blueprint_blueprint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='blueprint_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
