# Generated by Django 2.2.1 on 2020-04-22 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0023_auto_20200422_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Blueprint')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Process')),
            ],
        ),
    ]
