# Generated by Django 2.2.1 on 2020-04-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0024_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='boxid',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Blueprint'),
        ),
    ]
