# Generated by Django 2.2.1 on 2020-04-28 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapi', '0025_auto_20200424_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='blueprint',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='datum',
            name='node',
        ),
        migrations.AddField(
            model_name='datum',
            name='entity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='blueprint',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Blueprint'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.AddField(
            model_name='pin',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Experiment'),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Tag'),
        ),
    ]
