# Generated by Django 2.2.1 on 2020-06-30 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapi', '0027_auto_20200602_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datum',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='datum',
            name='finisher',
        ),
        migrations.RemoveField(
            model_name='datum',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='datum',
        ),
        migrations.AddField(
            model_name='datum',
            name='process',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Process'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datum',
            name='quantity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='definition',
            name='entity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapi.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='finisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='finisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
