# Generated by Django 2.2.1 on 2020-06-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0028_auto_20200630_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='finisher',
        ),
    ]
