# Generated by Django 2.2.1 on 2020-06-30 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0029_remove_entity_finisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datum',
            name='quantity',
        ),
        migrations.AddField(
            model_name='datum',
            name='quantity_x',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_x', to='webapi.Quantity'),
        ),
        migrations.AddField(
            model_name='datum',
            name='quantity_y',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_y', to='webapi.Quantity'),
        ),
        migrations.AddField(
            model_name='datum',
            name='quantity_z',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_z', to='webapi.Quantity'),
        ),
    ]
