# Generated by Django 2.2.1 on 2020-06-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0030_auto_20200630_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datum',
            name='process',
        ),
        migrations.AddField(
            model_name='datum',
            name='figure',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Figure'),
            preserve_default=False,
        ),
    ]
