# Generated by Django 2.2.1 on 2020-07-02 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0031_auto_20200630_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datum',
            name='quantity_x',
        ),
        migrations.RemoveField(
            model_name='datum',
            name='quantity_y',
        ),
        migrations.RemoveField(
            model_name='datum',
            name='quantity_z',
        ),
        migrations.AddField(
            model_name='datum',
            name='unit_x',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_x', to='webapi.Unit'),
        ),
        migrations.AddField(
            model_name='datum',
            name='unit_y',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_y', to='webapi.Unit'),
        ),
        migrations.AddField(
            model_name='datum',
            name='unit_z',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_z', to='webapi.Unit'),
        ),
    ]
