# Generated by Django 2.2.1 on 2020-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0033_auto_20200710_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
