# Generated by Django 2.2.1 on 2020-07-10 08:27

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0034_auto_20200710_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='value',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
