# Generated by Django 2.2.1 on 2020-07-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0035_description_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='value',
            new_name='values',
        ),
    ]
