# Generated by Django 2.2.1 on 2020-07-14 08:26

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0036_auto_20200710_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='entity',
        ),
        migrations.AddField(
            model_name='datum',
            name='is_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='description',
            name='entity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='is_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='candidates',
            field=django_mysql.models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Defaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', django_mysql.models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Item')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Process')),
            ],
        ),
    ]
