# Generated by Django 2.2.1 on 2020-07-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0037_auto_20200714_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='candidates',
        ),
    ]
