# Generated by Django 2.2.1 on 2020-07-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0038_remove_item_candidates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defaults',
            new_name='Default',
        ),
    ]
