# Generated by Django 2.2.1 on 2020-07-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0039_auto_20200714_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default',
            name='values',
        ),
    ]
