# Generated by Django 2.2.1 on 2020-07-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0040_remove_default_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
