# Generated by Django 2.2.1 on 2020-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0041_auto_20200716_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='is_condition',
            field=models.BooleanField(default=False),
        ),
    ]
