# Generated by Django 2.2.1 on 2020-07-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0042_default_is_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datum',
            name='is_condition',
        ),
        migrations.AddField(
            model_name='figure',
            name='is_condition',
            field=models.BooleanField(default=False),
        ),
    ]
