# Generated by Django 2.2.1 on 2021-02-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0044_headline_sentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metavalue',
            old_name='process',
            new_name='figure',
        ),
    ]
