# Generated by Django 2.2.1 on 2021-02-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0046_auto_20210216_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='cluster',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='description',
            name='cluster',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='figure',
            name='cluster',
            field=models.IntegerField(default=2),
        ),
    ]
