# Generated by Django 2.2.1 on 2021-02-16 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapi', '0048_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metavalue',
            new_name='Metadata',
        ),
    ]
