# Generated by Django 2.2.1 on 2021-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0052_image_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
