# Generated by Django 2.2.1 on 2021-02-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0053_auto_20210217_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='entityid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='entityid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='entityid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='webapi.Entity'),
            preserve_default=False,
        ),
    ]
