# Generated by Django 2.2.1 on 2021-02-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0054_auto_20210217_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='entityid',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='entityid',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='entityid',
            new_name='entity',
        ),
    ]
