# Generated by Django 2.2.1 on 2021-02-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0055_auto_20210218_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='cluster',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='sentence',
            name='cluster',
            field=models.IntegerField(default=2),
        ),
    ]
