# Generated by Django 2.2.1 on 2021-02-25 07:47

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0056_auto_20210225_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='value',
        ),
        migrations.AddField(
            model_name='metadata',
            name='values',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
