# Generated by Django 2.2.1 on 2021-03-05 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0057_auto_20210225_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='entity',
        ),
        migrations.AddField(
            model_name='product',
            name='experiment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='webapi.Experiment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Entity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapi.Product')),
            ],
        ),
    ]
