# Generated by Django 2.2.1 on 2021-03-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0059_node_node_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='concept',
            field=models.IntegerField(default=2),
        ),
    ]
