# Generated by Django 2.2.1 on 2021-03-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0060_node_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='concept',
        ),
        migrations.AddField(
            model_name='type',
            name='concept',
            field=models.IntegerField(default=2),
        ),
    ]
