# Generated by Django 2.2.1 on 2021-03-19 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0061_auto_20210317_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapi.Node'),
        ),
    ]
